version: '3'

services:

  telethon_downloader:
    image: darinirvana/telegraph-2-komga-format
    container_name: telegraph-2-komga-format
    restart: unless-stopped
    network_mode: host
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TG_BOT_TOKEN='
      - 'TZ=Asia/Shanghai'
      - 'DOWNLOAD_THREADS='
      - 'PROXY_URL='
    volumes:
      - /path/to/download:/download