version: '3'

services:

  telethon_downloader:
    image: darinirvana/telegraph-2-komga-format
    container_name: telegraph-2-komga-format
    restart: unless-stopped
    network_mode: host
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'BOT_TOKEN='
      - 'MY_USER_ID='
      - 'TZ=Asia/Shanghai'
      - 'TELEGRAPH_THREADS='
      - 'HTTP_PROXY='
    volumes:
      - /path/to/download:/media