version: '3'

services:

  neko-chan:
    image: darinirvana/neko-chan:latest
    container_name: neko-chan

    network_mode: host
    restart: on-failure

    build:
      context: ./
      dockerfile: Dockerfile

    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'BOT_TOKEN='
      - 'CF_WORKER_PROXY='
      - 'MY_USER_ID='
      - 'PROXY='
      - 'TELEGRAPH_THREADS='
      - 'TZ=Asia/Shanghai'

    volumes:
      - /localhost/path/to/media:/neko
      - /localhost/path/to/log:/logs